### ISSUE TITLE
error: root manifest not found

### ISSUE THREAD

**Issue by igor-makarov** [twodayslate/swift-package-registry#11]
Hi @twodayslate! 

The registry is looking good!

I've checked my own package, [BeaconKit](https://swiftpackageregistry.com/igor-makarov/BeaconKit) and it says `error: root manifest not found`. 

Any ideas? I've already installed the GH app to the repo.

Thanks!

**Comment by twodayslate** [comment]
It is taking your latest release which does not have a Package.swift file 

https://github.com/igor-makarov/BeaconKit/tree/49add3a7d7b1fa7a9a5bfd90768481c7dc2a5093

**Comment by igor-makarov** [comment]
Gotcha @twodayslate - turns out I was tagging releases but not publishing them as such in GitHub! Updated it now. 

Do you think it would be possible to include tags that are not "GitHub Releases" but would still be applicable when used with SwiftPM?

**Comment by twodayslate** [comment]
It's in the pipeline - see #5 

Sorry about that!
