### ISSUE TITLE
[Feature Request] Allow to update Swift package manually

### ISSUE THREAD

**Issue by MarcoEidinger** [twodayslate/swift-package-registry#15]
Repository owners might not be able to install GitHub App (e.g employer restrictions). Still, there should be a way to update Swift package when publishing a new release

Current implementation prohibits this

> Swift package will not update automatically unless the GitHub App is installed on the repository.

A solution would be to re-process package information when user [add](https://swiftpackageregistry.com/add) existing package

**Comment by twodayslate** [comment]
Currently this code is what prohibits the reprocessing. https://github.com/twodayslate/swift-package-registry/blob/master/lib/add.js#L57
There should be a check that the package actually has updates, and if it does, reprocess. 

I would consider #13 and #16 blockers for this

**Comment by MarcoEidinger** [comment]
I can have a look to introduce feature as part of PR but I would need some guidance on how to setup the project for testing. So far I figured out that postgres and a database named `spr` is required but the details (e.g. what tables, etc. ).

**Comment by twodayslate** [comment]
Take a look at [.env.example](https://github.com/twodayslate/swift-package-registry/blob/master/.env.example). You will need to fill in those environmental variables. 

You'll need to setup your own test GitHub App. 

The app is based off of [probot](https://probot.github.io/docs/).

The database should be auto created thanks to [sequelize](https://sequelize.org/).

**Comment by twodayslate** [comment]
This should be complete in e685aa00de580db514faeacc7a087e930c2e766e

Let me know if you have any issues
