### ISSUE TITLE
"Error processing" on swift package page

### ISSUE THREAD

**Issue by csjones** [twodayslate/swift-package-registry#22]
Hi 👋 

I see an "Error processing" message on the swift package page and I'm not exactly sure how I can fix the error: https://swiftpackageregistry.com/GigaBitcoin/secp256k1.swift

I think it has to with the fact I'm using submodules behind the scenes to build a c library before mapping it into swift.

<img width="1102" alt="Screen Shot 2020-09-03 at 4 40 39 PM" src="https://user-images.githubusercontent.com/637026/92183796-4b5eb800-ee04-11ea-98ad-e75df1bec2de.png">

Any guidance would be super helpful!

**Comment by csjones** [comment]
@twodayslate thoughts? :)

**Comment by twodayslate** [comment]
@csjones strange I didn’t get a notification for the original ticket. Thanks for @ing me. 

Could it be the sub modules?

**Comment by csjones** [comment]
> @csjones strange I didn’t get a notification for the original ticket. Thanks for @ing me.
> 
> It looks to be the sub modules. I’ll have to switch from pulling the GitHub archive to actually using git
> 
> Thanks for catching this edge case!

Thanks for the response! Is the change complicated?

**Comment by twodayslate** [comment]
Should be changing the wget to a git clone https://github.com/twodayslate/swift-package-registry/blob/master/lib/process.js#L178

**Comment by twodayslate** [comment]
@csjones Should be fixed in 93a309eab25a7f8f7851afdd331b7387dc2afd80

https://swiftpackageregistry.com/GigaBitcoin/secp256k1.swift

**Comment by csjones** [comment]
> @csjones Should be fixed in [93a309e](https://github.com/twodayslate/swift-package-registry/commit/93a309eab25a7f8f7851afdd331b7387dc2afd80)
> 
> https://swiftpackageregistry.com/GigaBitcoin/secp256k1.swift

Awesome, thank you for the fix! 😁
