### ISSUE TITLE
endpoint url to the list of packages

### ISSUE THREAD

**Issue by workingDog** [twodayslate/swift-package-registry#25]
what a great project. 

It would be good if there was an endpoint url, where external apps could 
fetch the list of all Swift Packages info, for example, a json list such as:

 [
 {
 "id": "uuidstring",
 "url": "https://github.com/..../xxxx.git",
 "repo": "repo name",
 "owner": "owner name",
 "description": "....",
 "archived": false
 "tagsUrl": "...",
 "htmlUrl": "...",
 "homepage": "...",
 "createdAt" : "...",
 "updatedAt": "...",
 "license": "...",
 "stargazersCount": 0,
 "tags": [...],
 
 "swiftVersions": ["5.2", "5.3"],
 "toolsVersion": "5.1"",
 "dependencies": [url1, url2,...],
 "platforms": [.iOS("13.0"), .macOS("10.15")]
 },
 ...
 ]
 
Alternatively, just the repo url plus the last 4 items, since these are difficult to obtained by parsing Package.swift. 

 [
 {
 "id": "uuidstring",
 "url": "https://github.com/..../xxxx.git",
 "swiftVersions": ["5.2", "5.3"],
 "toolsVersion": "5.1"",
 "dependencies": [url1, url2,...],
 "platforms": [.iOS("13.0"), .macOS("10.15")]
 },
 ...
 ]

**Comment by twodayslate** [comment]
The API can be accessed at /all.json and /owner/repo.json
